"""
Model Report Generator — PredictX
Reads all JSON result files produced by the pipeline and writes a
human-readable Markdown summary to results/model_report.md.

Run after the full pipeline has completed:
    python src/report.py

Output: results/model_report.md
"""

import json
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from custom_logging import logger
from exception import CustomException

RESULTS_DIR = Path(__file__).parent.parent / "results"

CV_SCORES_PATH    = RESULTS_DIR / "cv_scores.json"
EVAL_METRICS_PATH = RESULTS_DIR / "eval_metrics.json"
BEST_PARAMS_PATH  = RESULTS_DIR / "best_params.json"
SHAP_TOP10_PATH   = RESULTS_DIR / "shap_top10.json"
DRIFT_REPORT_PATH = RESULTS_DIR / "drift_report.json"
OUTPUT_PATH       = RESULTS_DIR / "model_report.md"


def _load(path: Path) -> dict | None:
    if path.exists():
        with open(path) as f:
            return json.load(f)
    return None


def build_report() -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines: list[str] = []

    lines += [
        "# PredictX — Model Performance Report",
        f"_Generated: {now}_",
        "",
        "---",
        "",
    ]

    # --- CV scores ---
    cv = _load(CV_SCORES_PATH)
    if cv:
        lines += [
            "## Cross-Validation Results",
            "",
            "| Fold | Macro F1 |",
            "|------|----------|",
        ]
        for i, s in enumerate(cv.get("per_fold_f1", []), 1):
            lines.append(f"| {i} | {s:.4f} |")
        lines += [
            f"| **Mean** | **{cv['mean_macro_f1']:.4f}** |",
            f"| **Std**  | {cv['std_macro_f1']:.4f} |",
            "",
        ]
    else:
        lines += ["## Cross-Validation Results", "", "_cv_scores.json not found — run train.py_", ""]

    # --- Eval metrics ---
    ev = _load(EVAL_METRICS_PATH)
    if ev:
        lines += [
            "## Evaluation on Noisy Test Set",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Default threshold (0.5) Macro F1 | {ev['default_threshold_macro_f1']:.4f} |",
            f"| Tuned threshold | {ev['tuned_threshold']:.4f} |",
            f"| Tuned threshold Macro F1 | {ev['tuned_threshold_macro_f1']:.4f} |",
            f"| Noise scale (σ) | {ev['noise_scale']} × feature std |",
            "",
        ]
    else:
        lines += ["## Evaluation on Noisy Test Set", "", "_eval_metrics.json not found — run evaluate.py_", ""]

    # --- Best params ---
    bp = _load(BEST_PARAMS_PATH)
    if bp:
        lines += [
            "## Tuned Hyperparameters",
            "",
            f"Best CV Macro F1 from Optuna: **{bp.get('macro_f1', 'N/A')}**",
            "",
            "| Parameter | Value |",
            "|-----------|-------|",
        ]
        for k, v in bp.get("params", {}).items():
            lines.append(f"| `{k}` | {v} |")
        lines.append("")
    else:
        lines += ["## Tuned Hyperparameters", "", "_best_params.json not found — run tune.py_", ""]

    # --- SHAP top-10 ---
    shap = _load(SHAP_TOP10_PATH)
    if shap:
        lines += [
            "## Top-10 Features by SHAP Importance",
            "",
            "| Rank | Feature | Mean |SHAP| |",
            "|------|---------|--------------|",
        ]
        for rank, (feat, val) in enumerate(shap.items(), 1):
            lines.append(f"| {rank} | `{feat}` | {val:.4f} |")
        lines.append("")
    else:
        lines += ["## Top-10 Features by SHAP Importance", "", "_shap_top10.json not found — run explain.py_", ""]

    # --- Drift report ---
    drift = _load(DRIFT_REPORT_PATH)
    if drift:
        status = "⚠ Drift detected" if drift["drift_detected"] else "✓ No drift detected"
        lines += [
            "## Feature Drift Report",
            "",
            f"**Status:** {status}  ",
            f"**Alpha:** {drift['alpha']}  ",
            f"**Drifted features:** {', '.join(drift['drifted_features']) or 'None'}",
            "",
            "| Feature | KS Statistic | p-value | Drifted |",
            "|---------|-------------|---------|---------|",
        ]
        for feat, info in drift.get("features", {}).items():
            flag = "⚠ Yes" if info["drifted"] else "No"
            lines.append(f"| `{feat}` | {info['ks_statistic']:.4f} | {info['p_value']:.4f} | {flag} |")
        lines.append("")

    lines += ["---", "", "_Report generated by `src/report.py`_", ""]
    return "\n".join(lines)


def main() -> None:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    report_md = build_report()
    OUTPUT_PATH.write_text(report_md, encoding="utf-8")
    logger.info(f"Saved model report -> {OUTPUT_PATH}")
    print(report_md)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        raise CustomException(e, sys)
